/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/apis/magosproject.io/v1alpha1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project resources */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.Project"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/magosproject.io/v1alpha1/projects/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Project events
         * @description Server-Sent Events stream of Project changes. Each event is a JSON-encoded ProjectEvent.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["service.ProjectEvent"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/magosproject.io/v1alpha1/projects/{namespace}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project resource */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Namespace */
                    namespace: string;
                    /** @description Name */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.Project"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/magosproject.io/v1alpha1/rollouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rollout resources */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.Rollout"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/magosproject.io/v1alpha1/rollouts/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Rollout events
         * @description Server-Sent Events stream of Rollout changes. Each event is a JSON-encoded RolloutEvent.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["service.RolloutEvent"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/magosproject.io/v1alpha1/rollouts/{namespace}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rollout resource */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Namespace */
                    namespace: string;
                    /** @description Name */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.Rollout"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/magosproject.io/v1alpha1/variablesets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List VariableSet resources */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.VariableSet"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/magosproject.io/v1alpha1/variablesets/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream VariableSet events
         * @description Server-Sent Events stream of VariableSet changes. Each event is a JSON-encoded VariableSetEvent.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["service.VariableSetEvent"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/magosproject.io/v1alpha1/variablesets/{namespace}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get VariableSet resource */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Namespace */
                    namespace: string;
                    /** @description Name */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.VariableSet"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/magosproject.io/v1alpha1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspace resources */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.Workspace"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/magosproject.io/v1alpha1/workspaces/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Workspace events
         * @description Server-Sent Events stream of Workspace changes. Each event is a JSON-encoded WorkspaceEvent. Use ?projectRef=name to filter by project.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by project name */
                    projectRef?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["service.WorkspaceEvent"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apis/magosproject.io/v1alpha1/workspaces/{namespace}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace resource */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Namespace */
                    namespace: string;
                    /** @description Name */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.Workspace"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["handlers.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "handlers.ErrorResponse": {
            error?: string;
        };
        "handlers.Project": {
            metadata?: components["schemas"]["v1.ObjectMeta"];
            spec?: components["schemas"]["v1alpha1.ProjectSpec"];
            status?: components["schemas"]["v1alpha1.ProjectStatus"];
        };
        "handlers.Rollout": {
            metadata?: components["schemas"]["v1.ObjectMeta"];
            spec?: components["schemas"]["v1alpha1.RolloutSpec"];
            status?: components["schemas"]["v1alpha1.RolloutStatus"];
        };
        "handlers.VariableSet": {
            metadata?: components["schemas"]["v1.ObjectMeta"];
            spec?: components["schemas"]["v1alpha1.VariableSetSpec"];
            status?: components["schemas"]["v1alpha1.VariableSetStatus"];
        };
        "handlers.Workspace": {
            metadata?: components["schemas"]["v1.ObjectMeta"];
            spec?: components["schemas"]["v1alpha1.WorkspaceSpec"];
            status?: components["schemas"]["v1alpha1.WorkspaceStatus"];
        };
        /**
         * @description status of the condition, one of True, False, Unknown.
         *     +required
         *     +kubebuilder:validation:Required
         *     +kubebuilder:validation:Enum=True;False;Unknown
         * @enum {string}
         */
        "k8s_io_apimachinery_pkg_apis_meta_v1.ConditionStatus": "True" | "False" | "Unknown";
        "service.ProjectEvent": {
            object?: components["schemas"]["v1alpha1.Project"];
            type?: components["schemas"]["watch.EventType"];
        };
        "service.RolloutEvent": {
            object?: components["schemas"]["v1alpha1.Rollout"];
            type?: components["schemas"]["watch.EventType"];
        };
        "service.VariableSetEvent": {
            object?: components["schemas"]["v1alpha1.VariableSet"];
            type?: components["schemas"]["watch.EventType"];
        };
        "service.WorkspaceEvent": {
            object?: components["schemas"]["v1alpha1.Workspace"];
            type?: components["schemas"]["watch.EventType"];
        };
        "v1.Condition": {
            /**
             * @description lastTransitionTime is the last time the condition transitioned from one status to another.
             *     This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
             *     +required
             *     +kubebuilder:validation:Required
             *     +kubebuilder:validation:Type=string
             *     +kubebuilder:validation:Format=date-time
             */
            lastTransitionTime?: string;
            /**
             * @description message is a human readable message indicating details about the transition.
             *     This may be an empty string.
             *     +required
             *     +kubebuilder:validation:Required
             *     +kubebuilder:validation:MaxLength=32768
             */
            message?: string;
            /**
             * @description observedGeneration represents the .metadata.generation that the condition was set based upon.
             *     For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
             *     with respect to the current state of the instance.
             *     +optional
             *     +kubebuilder:validation:Minimum=0
             */
            observedGeneration?: number;
            /**
             * @description reason contains a programmatic identifier indicating the reason for the condition's last transition.
             *     Producers of specific condition types may define expected values and meanings for this field,
             *     and whether the values are considered a guaranteed API.
             *     The value should be a CamelCase string.
             *     This field may not be empty.
             *     +required
             *     +kubebuilder:validation:Required
             *     +kubebuilder:validation:MaxLength=1024
             *     +kubebuilder:validation:MinLength=1
             *     +kubebuilder:validation:Pattern=`^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$`
             */
            reason?: string;
            status?: components["schemas"]["k8s_io_apimachinery_pkg_apis_meta_v1.ConditionStatus"];
            /**
             * @description type of condition in CamelCase or in foo.example.com/CamelCase.
             *     ---
             *     Many .condition.type values are consistent across resources like Available, but because arbitrary conditions can be
             *     useful (see .node.status.conditions), the ability to deconflict is important.
             *     The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
             *     +required
             *     +kubebuilder:validation:Required
             *     +kubebuilder:validation:Pattern=`^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*\/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$`
             *     +kubebuilder:validation:MaxLength=316
             */
            type?: string;
        };
        /**
         * @description FieldsV1 holds the first JSON version format as described in the "FieldsV1" type.
         *     +optional
         */
        "v1.FieldsV1": Record<string, never>;
        /**
         * @description Selector to match workspaces for this step
         *     +required
         */
        "v1.LabelSelector": {
            /**
             * @description matchExpressions is a list of label selector requirements. The requirements are ANDed.
             *     +optional
             *     +listType=atomic
             */
            matchExpressions?: components["schemas"]["v1.LabelSelectorRequirement"][];
            /**
             * @description matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
             *     map is equivalent to an element of matchExpressions, whose key field is "key", the
             *     operator is "In", and the values array contains only "value". The requirements are ANDed.
             *     +optional
             */
            matchLabels?: {
                [key: string]: string;
            };
        };
        /**
         * @description operator represents a key's relationship to a set of values.
         *     Valid operators are In, NotIn, Exists and DoesNotExist.
         * @enum {string}
         */
        "v1.LabelSelectorOperator": "In" | "NotIn" | "Exists" | "DoesNotExist";
        "v1.LabelSelectorRequirement": {
            /** @description key is the label key that the selector applies to. */
            key?: string;
            operator?: components["schemas"]["v1.LabelSelectorOperator"];
            /**
             * @description values is an array of string values. If the operator is In or NotIn,
             *     the values array must be non-empty. If the operator is Exists or DoesNotExist,
             *     the values array must be empty. This array is replaced during a strategic
             *     merge patch.
             *     +optional
             *     +listType=atomic
             */
            values?: string[];
        };
        "v1.ManagedFieldsEntry": {
            /**
             * @description APIVersion defines the version of this resource that this field set
             *     applies to. The format is "group/version" just like the top-level
             *     APIVersion field. It is necessary to track the version of a field
             *     set because it cannot be automatically converted.
             */
            apiVersion?: string;
            /**
             * @description FieldsType is the discriminator for the different fields format and version.
             *     There is currently only one possible value: "FieldsV1"
             */
            fieldsType?: string;
            fieldsV1?: components["schemas"]["v1.FieldsV1"];
            /** @description Manager is an identifier of the workflow managing these fields. */
            manager?: string;
            operation?: components["schemas"]["v1.ManagedFieldsOperationType"];
            /**
             * @description Subresource is the name of the subresource used to update that object, or
             *     empty string if the object was updated through the main resource. The
             *     value of this field is used to distinguish between managers, even if they
             *     share the same name. For example, a status update will be distinct from a
             *     regular update using the same manager name.
             *     Note that the APIVersion field is not related to the Subresource field and
             *     it always corresponds to the version of the main resource.
             */
            subresource?: string;
            /**
             * @description Time is the timestamp of when the ManagedFields entry was added. The
             *     timestamp will also be updated if a field is added, the manager
             *     changes any of the owned fields value or removes a field. The
             *     timestamp does not update when a field is removed from the entry
             *     because another manager took it over.
             *     +optional
             */
            time?: string;
        };
        /**
         * @description Operation is the type of operation which lead to this ManagedFieldsEntry being created.
         *     The only valid values for this field are 'Apply' and 'Update'.
         * @enum {string}
         */
        "v1.ManagedFieldsOperationType": "Apply" | "Update";
        /**
         * @description metadata is a standard object metadata
         *     +optional
         */
        "v1.ObjectMeta": {
            /**
             * @description Annotations is an unstructured key value map stored with a resource that may be
             *     set by external tools to store and retrieve arbitrary metadata. They are not
             *     queryable and should be preserved when modifying objects.
             *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations
             *     +optional
             */
            annotations?: {
                [key: string]: string;
            };
            /**
             * @description CreationTimestamp is a timestamp representing the server time when this object was
             *     created. It is not guaranteed to be set in happens-before order across separate operations.
             *     Clients may not set this value. It is represented in RFC3339 form and is in UTC.
             *
             *     Populated by the system.
             *     Read-only.
             *     Null for lists.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
             *     +optional
             */
            creationTimestamp?: string;
            /**
             * @description Number of seconds allowed for this object to gracefully terminate before
             *     it will be removed from the system. Only set when deletionTimestamp is also set.
             *     May only be shortened.
             *     Read-only.
             *     +optional
             */
            deletionGracePeriodSeconds?: number;
            /**
             * @description DeletionTimestamp is RFC 3339 date and time at which this resource will be deleted. This
             *     field is set by the server when a graceful deletion is requested by the user, and is not
             *     directly settable by a client. The resource is expected to be deleted (no longer visible
             *     from resource lists, and not reachable by name) after the time in this field, once the
             *     finalizers list is empty. As long as the finalizers list contains items, deletion is blocked.
             *     Once the deletionTimestamp is set, this value may not be unset or be set further into the
             *     future, although it may be shortened or the resource may be deleted prior to this time.
             *     For example, a user may request that a pod is deleted in 30 seconds. The Kubelet will react
             *     by sending a graceful termination signal to the containers in the pod. After that 30 seconds,
             *     the Kubelet will send a hard termination signal (SIGKILL) to the container and after cleanup,
             *     remove the pod from the API. In the presence of network partitions, this object may still
             *     exist after this timestamp, until an administrator or automated process can determine the
             *     resource is fully terminated.
             *     If not set, graceful deletion of the object has not been requested.
             *
             *     Populated by the system when a graceful deletion is requested.
             *     Read-only.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
             *     +optional
             */
            deletionTimestamp?: string;
            /**
             * @description Must be empty before the object is deleted from the registry. Each entry
             *     is an identifier for the responsible component that will remove the entry
             *     from the list. If the deletionTimestamp of the object is non-nil, entries
             *     in this list can only be removed.
             *     Finalizers may be processed and removed in any order.  Order is NOT enforced
             *     because it introduces significant risk of stuck finalizers.
             *     finalizers is a shared field, any actor with permission can reorder it.
             *     If the finalizer list is processed in order, then this can lead to a situation
             *     in which the component responsible for the first finalizer in the list is
             *     waiting for a signal (field value, external system, or other) produced by a
             *     component responsible for a finalizer later in the list, resulting in a deadlock.
             *     Without enforced ordering finalizers are free to order amongst themselves and
             *     are not vulnerable to ordering changes in the list.
             *     +optional
             *     +patchStrategy=merge
             *     +listType=set
             */
            finalizers?: string[];
            /**
             * @description GenerateName is an optional prefix, used by the server, to generate a unique
             *     name ONLY IF the Name field has not been provided.
             *     If this field is used, the name returned to the client will be different
             *     than the name passed. This value will also be combined with a unique suffix.
             *     The provided value has the same validation rules as the Name field,
             *     and may be truncated by the length of the suffix required to make the value
             *     unique on the server.
             *
             *     If this field is specified and the generated name exists, the server will return a 409.
             *
             *     Applied only if Name is not specified.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency
             *     +optional
             */
            generateName?: string;
            /**
             * @description A sequence number representing a specific generation of the desired state.
             *     Populated by the system. Read-only.
             *     +optional
             */
            generation?: number;
            /**
             * @description Map of string keys and values that can be used to organize and categorize
             *     (scope and select) objects. May match selectors of replication controllers
             *     and services.
             *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
             *     +optional
             */
            labels?: {
                [key: string]: string;
            };
            /**
             * @description ManagedFields maps workflow-id and version to the set of fields
             *     that are managed by that workflow. This is mostly for internal
             *     housekeeping, and users typically shouldn't need to set or
             *     understand this field. A workflow can be the user's name, a
             *     controller's name, or the name of a specific apply path like
             *     "ci-cd". The set of fields is always in the version that the
             *     workflow used when modifying the object.
             *
             *     +optional
             *     +listType=atomic
             */
            managedFields?: components["schemas"]["v1.ManagedFieldsEntry"][];
            /**
             * @description Name must be unique within a namespace. Is required when creating resources, although
             *     some resources may allow a client to request the generation of an appropriate name
             *     automatically. Name is primarily intended for creation idempotence and configuration
             *     definition.
             *     Cannot be updated.
             *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
             *     +optional
             */
            name?: string;
            /**
             * @description Namespace defines the space within which each name must be unique. An empty namespace is
             *     equivalent to the "default" namespace, but "default" is the canonical representation.
             *     Not all objects are required to be scoped to a namespace - the value of this field for
             *     those objects will be empty.
             *
             *     Must be a DNS_LABEL.
             *     Cannot be updated.
             *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces
             *     +optional
             */
            namespace?: string;
            /**
             * @description List of objects depended by this object. If ALL objects in the list have
             *     been deleted, this object will be garbage collected. If this object is managed by a controller,
             *     then an entry in this list will point to this controller, with the controller field set to true.
             *     There cannot be more than one managing controller.
             *     +optional
             *     +patchMergeKey=uid
             *     +patchStrategy=merge
             *     +listType=map
             *     +listMapKey=uid
             */
            ownerReferences?: components["schemas"]["v1.OwnerReference"][];
            /**
             * @description An opaque value that represents the internal version of this object that can
             *     be used by clients to determine when objects have changed. May be used for optimistic
             *     concurrency, change detection, and the watch operation on a resource or set of resources.
             *     Clients must treat these values as opaque and passed unmodified back to the server.
             *     They may only be valid for a particular resource or set of resources.
             *
             *     Populated by the system.
             *     Read-only.
             *     Value must be treated as opaque by clients and .
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
             *     +optional
             */
            resourceVersion?: string;
            /**
             * @description Deprecated: selfLink is a legacy read-only field that is no longer populated by the system.
             *     +optional
             */
            selfLink?: string;
            /**
             * @description UID is the unique in time and space value for this object. It is typically generated by
             *     the server on successful creation of a resource and is not allowed to change on PUT
             *     operations.
             *
             *     Populated by the system.
             *     Read-only.
             *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
             *     +optional
             */
            uid?: string;
        };
        "v1.OwnerReference": {
            /** @description API version of the referent. */
            apiVersion?: string;
            /**
             * @description If true, AND if the owner has the "foregroundDeletion" finalizer, then
             *     the owner cannot be deleted from the key-value store until this
             *     reference is removed.
             *     See https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion
             *     for how the garbage collector interacts with this field and enforces the foreground deletion.
             *     Defaults to false.
             *     To set this field, a user needs "delete" permission of the owner,
             *     otherwise 422 (Unprocessable Entity) will be returned.
             *     +optional
             */
            blockOwnerDeletion?: boolean;
            /**
             * @description If true, this reference points to the managing controller.
             *     +optional
             */
            controller?: boolean;
            /**
             * @description Kind of the referent.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: string;
            /**
             * @description Name of the referent.
             *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
             */
            name?: string;
            /**
             * @description UID of the referent.
             *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
             */
            uid?: string;
        };
        /**
         * @description Apply holds overrides applied only to apply Jobs.
         *     +optional
         */
        "v1alpha1.JobOverrides": {
            /**
             * @description Annotations to add to the Job's pod template. Merged on top of
             *     spec.annotations; values here win on conflict.
             *     +optional
             */
            annotations?: {
                [key: string]: string;
            };
            /**
             * @description TimeoutSeconds sets the activeDeadlineSeconds on the Kubernetes Job.
             *     If the Job does not finish within this duration, Kubernetes marks it
             *     as Failed, preventing a Workspace from being stuck in Planning or
             *     Applying indefinitely. When unset, DefaultJobTimeoutSeconds (86400) is
             *     used.
             *     +optional
             */
            timeoutSeconds?: number;
        };
        /**
         * @description Phase represents the current phase of the Workspace
         *     +optional
         * @enum {string}
         */
        "v1alpha1.Phase": "Pending" | "Reconciling" | "Ready" | "Idle" | "Planning" | "Planned" | "Applying" | "Applied" | "Failed" | "Deleting";
        "v1alpha1.Project": {
            metadata?: components["schemas"]["v1.ObjectMeta"];
            spec?: components["schemas"]["v1alpha1.ProjectSpec"];
            status?: components["schemas"]["v1alpha1.ProjectStatus"];
        };
        /**
         * @description ProjectRef is a reference to the project this workspace belongs to
         *     +required
         */
        "v1alpha1.ProjectReference": {
            /**
             * @description Name of the Project.
             *     +required
             *     +kubebuilder:validation:MinLength=1
             */
            name?: string;
        };
        /**
         * @description spec defines the desired state of Project
         *     +required
         */
        "v1alpha1.ProjectSpec": {
            /**
             * @description Description provides a human-readable description of the project's purpose.
             *     +optional
             */
            description?: string;
            /**
             * @description VariableSetRef references one or more VariableSets to be applied to all Workspaces within this Project.
             *     +optional
             */
            variableSetRef?: components["schemas"]["v1alpha1.VariableSetReference"][];
        };
        /**
         * @description status defines the observed state of Project
         *     +optional
         */
        "v1alpha1.ProjectStatus": {
            /**
             * @description conditions represent the current state of the Project resource.
             *     Each condition has a unique type and reflects the status of a specific aspect of the resource.
             *
             *     Standard condition types include:
             *     - "Available": the resource is fully functional
             *     - "Progressing": the resource is being created or updated
             *     - "Degraded": the resource failed to reach or maintain its desired state
             *
             *     The status of each condition is one of True, False, or Unknown.
             *     +listType=map
             *     +listMapKey=type
             *     +optional
             */
            conditions?: components["schemas"]["v1.Condition"][];
            /**
             * @description LastReconcileTime is the timestamp of the last reconciliation
             *     +optional
             */
            lastReconcileTime?: string;
            /**
             * @description Message is a human-readable explanation of the current phase
             *     +optional
             */
            message?: string;
            phase?: components["schemas"]["v1alpha1.Phase"];
            /**
             * @description Reason is a brief CamelCase string explaining the current phase
             *     +optional
             */
            reason?: string;
        };
        "v1alpha1.Rollout": {
            metadata?: components["schemas"]["v1.ObjectMeta"];
            spec?: components["schemas"]["v1alpha1.RolloutSpec"];
            status?: components["schemas"]["v1alpha1.RolloutStatus"];
        };
        /**
         * @description spec defines the desired state of Rollout
         *     +required
         */
        "v1alpha1.RolloutSpec": {
            /**
             * @description ProjectRef is a reference to the project this rollout orchestrates
             *     +required
             */
            projectRef?: string;
            strategy?: components["schemas"]["v1alpha1.RolloutStrategy"];
        };
        /**
         * @description status defines the observed state of Rollout
         *     +optional
         */
        "v1alpha1.RolloutStatus": {
            /**
             * @description conditions represent the current state of the Rollout resource.
             *     +listType=map
             *     +listMapKey=type
             *     +optional
             */
            conditions?: components["schemas"]["v1.Condition"][];
            /**
             * @description CurrentStep is the index of the currently executing step
             *     +optional
             */
            currentStep?: number;
            /**
             * @description LastReconcileTime is the timestamp of the last reconciliation
             *     +optional
             */
            lastReconcileTime?: string;
            /**
             * @description Message is a human-readable explanation of the current phase
             *     +optional
             */
            message?: string;
            phase?: components["schemas"]["v1alpha1.Phase"];
            /**
             * @description Reason is a brief CamelCase string explaining the current phase
             *     +optional
             */
            reason?: string;
        };
        "v1alpha1.RolloutStep": {
            /**
             * @description Name of the step
             *     +required
             */
            name?: string;
            selector?: components["schemas"]["v1.LabelSelector"];
        };
        /**
         * @description Strategy defines the rollout execution plan
         *     +required
         */
        "v1alpha1.RolloutStrategy": {
            /**
             * @description Steps defines the sequential stages of the rollout
             *     +required
             */
            steps?: components["schemas"]["v1alpha1.RolloutStep"][];
        };
        /**
         * @description Source defines the Git repository configuration
         *     +required
         */
        "v1alpha1.SourceSpec": {
            /**
             * @description Path is the directory path within the Git repository
             *     +optional
             *     +kubebuilder:default="."
             */
            path?: string;
            /**
             * @description RepoURL is the URL of the Git repository to clone
             *     +required
             */
            repoURL?: string;
            /**
             * @description TargetRevision defines the commit, tag, or branch to checkout
             *     +required
             */
            targetRevision?: string;
        };
        /**
         * @description Terraform defines the Terraform or OpenTofu configuration
         *     +required
         */
        "v1alpha1.TerraformSpec": {
            /**
             * @description TfvarsPath is the path to the tfvars file within the repository
             *     +optional
             */
            tfvarsPath?: string;
            /**
             * @description Version is the Terraform or OpenTofu version to use
             *     +required
             */
            version?: string;
        };
        "v1alpha1.VariableSet": {
            metadata?: components["schemas"]["v1.ObjectMeta"];
            spec?: components["schemas"]["v1alpha1.VariableSetSpec"];
            status?: components["schemas"]["v1alpha1.VariableSetStatus"];
        };
        "v1alpha1.VariableSetReference": {
            /**
             * @description Name of the VariableSet.
             *     +required
             *     +kubebuilder:validation:MinLength=1
             */
            name?: string;
        };
        /**
         * @description spec defines the desired state of VariableSet
         *     +required
         */
        "v1alpha1.VariableSetSpec": {
            /**
             * @description foo is an example field of VariableSet. Edit variableset_types.go to remove/update
             *     +optional
             */
            foo?: string;
        };
        /**
         * @description status defines the observed state of VariableSet
         *     +optional
         */
        "v1alpha1.VariableSetStatus": {
            /**
             * @description conditions represent the current state of the VariableSet resource.
             *     Each condition has a unique type and reflects the status of a specific aspect of the resource.
             *
             *     Standard condition types include:
             *     - "Available": the resource is fully functional
             *     - "Progressing": the resource is being created or updated
             *     - "Degraded": the resource failed to reach or maintain its desired state
             *
             *     The status of each condition is one of True, False, or Unknown.
             *     +listType=map
             *     +listMapKey=type
             *     +optional
             */
            conditions?: components["schemas"]["v1.Condition"][];
        };
        "v1alpha1.Workspace": {
            metadata?: components["schemas"]["v1.ObjectMeta"];
            spec?: components["schemas"]["v1alpha1.WorkspaceSpec"];
            status?: components["schemas"]["v1alpha1.WorkspaceStatus"];
        };
        /**
         * @description spec defines the desired state of Workspace
         *     +required
         */
        "v1alpha1.WorkspaceSpec": {
            /**
             * @description Annotations to propagate to both plan and apply Job pod templates.
             *     Per-phase annotations in spec.plan or spec.apply take precedence on conflict.
             *     +optional
             */
            annotations?: {
                [key: string]: string;
            };
            apply?: components["schemas"]["v1alpha1.JobOverrides"];
            /**
             * @description AutoApply dictates whether the workspace should automatically apply after a successful plan
             *     +optional
             *     +kubebuilder:default=true
             */
            autoApply?: boolean;
            plan?: components["schemas"]["v1alpha1.JobOverrides"];
            projectRef?: components["schemas"]["v1alpha1.ProjectReference"];
            source?: components["schemas"]["v1alpha1.SourceSpec"];
            terraform?: components["schemas"]["v1alpha1.TerraformSpec"];
        };
        /**
         * @description status defines the observed state of Workspace
         *     +optional
         */
        "v1alpha1.WorkspaceStatus": {
            /**
             * @description conditions represent the current state of the Workspace resource.
             *     Each condition has a unique type and reflects the status of a specific aspect of the resource.
             *
             *     Standard condition types include:
             *     - "Available": the resource is fully functional
             *     - "Progressing": the resource is being created or updated
             *     - "Degraded": the resource failed to reach or maintain its desired state
             *
             *     The status of each condition is one of True, False, or Unknown.
             *     +listType=map
             *     +listMapKey=type
             *     +optional
             */
            conditions?: components["schemas"]["v1.Condition"][];
            /**
             * @description LastReconcileTime is the timestamp of the last reconciliation
             *     +optional
             */
            lastReconcileTime?: string;
            /**
             * @description Message is a human-readable explanation of the current phase
             *     +optional
             */
            message?: string;
            /**
             * @description NextReconcileTime is the expected time of the next scheduled reconciliation
             *     +optional
             */
            nextReconcileTime?: string;
            /**
             * @description ObservedRevision is the git revision that was most recently observed/applied
             *     +optional
             */
            observedRevision?: string;
            phase?: components["schemas"]["v1alpha1.Phase"];
            /**
             * @description Reason is a brief CamelCase string explaining the current phase
             *     +optional
             */
            reason?: string;
        };
        /** @enum {string} */
        "watch.EventType": "ADDED" | "MODIFIED" | "DELETED" | "BOOKMARK" | "ERROR";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
