apiVersion: v1
kind: Namespace
metadata:
  name: money-movement
  labels:
    app.kubernetes.io/part-of: money-movement-platform
    app.kubernetes.io/managed-by: magos
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: magos-job
  namespace: money-movement
  labels:
    app.kubernetes.io/part-of: money-movement-platform
    app.kubernetes.io/managed-by: magos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: magos-job-money-movement
  labels:
    app.kubernetes.io/part-of: money-movement-platform
    app.kubernetes.io/managed-by: magos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: magos-job
subjects:
- kind: ServiceAccount
  name: magos-job
  namespace: money-movement
