apiVersion: magosproject.io/v1alpha1
kind: Workspace
metadata:
  name: settlement-gateway-staging
  namespace: money-movement
  labels:
    app.kubernetes.io/part-of: money-movement-platform
    app.kubernetes.io/managed-by: magos
    env: staging
    service: settlement-gateway
  annotations:
    magosproject.io/reconcile-interval: "1800s"
spec:
  projectRef:
    name: money-movement
  autoApply: true
  source:
    repoURL: https://github.com/magosproject/demo.git
    targetRevision: main
    path: .
  terraform:
    version: "1.14.8"
    tfvarsPath: env/staging/vars.tfvars
