version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/api"
      - "/hack/tools"
    schedule:
      interval: "weekly"
    ignore:
    # these two forked dependencies are manually updated/managed
    - dependency-name: "github.com/magosproject/hc-install"
      versions: [">= 0.10.0"]
    - dependency-name: "github.com/magosproject/terraform-exec"
      versions: [">= 0.26.0"]
    groups:
      all-deps:
        applies-to: version-updates
        patterns:
          - "*"
      all-security-deps:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/ui"
    schedule:
      interval: "weekly"
    groups:
      npm-deps:
        patterns:
          - "*"
