apiVersion: magosproject.io/v1alpha1
kind: Workspace
metadata:
  name: settlement-prod
  namespace: default
  labels:
    env: prod
  annotations:
    magosproject.io/reconcile-interval: "120s"
spec:
  projectRef:
    name: payments-platform
  serviceAccountName: magos-job
  validation:
    policySelector:
      matchLabels:
        policy.magosproject.io/category: compliance
  source:
    repoURL: https://github.com/magosproject/demo.git
    targetRevision: main
    path: .
  terraform:
    version: "1.14.8"
    tfvarsPath: env/prod/vars.tfvars
