apiVersion: magosproject.io/v1alpha1
kind: Workspace
metadata:
  name: demo-staging
  namespace: demo
  annotations:
    magosproject.io/reconcile-interval: "5m"
spec:
  source:
    repoURL: https://github.com/magosproject/demo.git
    targetRevision: main
    path: .
  terraform:
    version: "1.14.0"
    tfvarsPath: env/staging/vars.tfvars
