apiVersion: magosproject.io/v1alpha1
kind: Workspace
metadata:
  name: edge-network-staging
  namespace: marketplace-edge
  labels:
    app.kubernetes.io/part-of: marketplace-platform
    app.kubernetes.io/managed-by: magos
    env: staging
  annotations:
    magosproject.io/reconcile-interval: "1800s"
spec:
  projectRef:
    name: marketplace-edge
  autoApply: true
  source:
    repoURL: https://github.com/magosproject/demo.git
    targetRevision: main
    path: .
  terraform:
    version: "1.14.8"
    tfvarsPath: env/staging/vars.tfvars
