apiVersion: v1
kind: Service
metadata:
  name: ui-server-service
  namespace: system
  labels:
    app: magos-ui
    app.kubernetes.io/name: magos
    app.kubernetes.io/component: magos-ui
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    control-plane: ui-server
    app.kubernetes.io/name: magos

