apiVersion: magosproject.io/v1alpha1
kind: Rollout
metadata:
  name: networking-with-failed-policies # Must match the projectRef exactly due to our CEL validation rule!
  namespace: default
spec:
  projectRef: networking-with-failed-policies
  strategy:
    steps:
      - name: dev
        selector:
          matchLabels:
            env: dev
      - name: staging
        selector:
          matchLabels:
            env: staging
      - name: prod
        selector:
          matchLabels:
            env: prod
