{{- if and .Values.ui.enabled .Values.ui.ingress.enabled .Values.ui.ingress.tls.enabled .Values.ui.ingress.tls.selfSignedCert }}
{{- include "magos.validate" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "magos.fullname" . }}-ui-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "magos.labels" . | nindent 4 }}
    {{- include "magos.ui.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ quote .Values.ui.host }}
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: magos-selfsigned-cert-issuer
  secretName: {{ .Values.ui.ingress.tls.secretName }}
{{- end }}
