{{- include "magos.validate" . -}}
{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "magos.fullname" . }}-api
  labels:
    {{- include "magos.labels" . | nindent 4 }}
    {{- include "magos.api.labels" . | nindent 4 }}
    {{- with (mergeOverwrite (deepCopy (default dict .Values.global.labels)) (.Values.api.labels | default dict)) }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  {{- include "magos.annotations" (dict "root" . "annotations" .Values.api.annotations) | nindent 2 }}
spec:
  replicas: {{ .Values.api.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "magos.selectorLabels" . | nindent 6 }}
      {{- include "magos.api.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "magos.labels" . | nindent 8 }}
        {{- include "magos.api.labels" . | nindent 8 }}
        {{- with (mergeOverwrite (deepCopy (default dict .Values.global.podLabels)) (.Values.api.podLabels | default dict)) }}
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      {{- with (mergeOverwrite (deepCopy (default dict .Values.global.podAnnotations)) (.Values.api.podAnnotations | default dict)) }}
      annotations:
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "magos.apiServiceAccountName" . }}
      {{- with .Values.api.securityContext | default .Values.global.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: api
        image: {{ include "magos.api.image" . }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              containerName: api
              divisor: "1"
              resource: limits.memory
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              containerName: api
              divisor: "1"
              resource: {{ include "magos.selectCpuResourceField" (dict "resources" .Values.api.resources) }}
        {{- include "magos.logstoreEnv" . | nindent 8 }}
        {{- include "magos.postgresEnv" . | nindent 8 }}
        {{- with (concat (default list .Values.global.env) (default list .Values.api.env)) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with (concat (default list .Values.global.envFrom) (default list .Values.api.envFrom)) }}
        envFrom:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.api.containerSecurityContext | default .Values.global.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.api.probes.enabled }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        {{- end }}
        resources:
          {{- toYaml .Values.api.resources | nindent 10 }}
        {{- if or .Values.api.cabundle.configMapName .Values.api.cabundle.secretName }}
        volumeMounts:
        - name: certs
          mountPath: /etc/ssl/certs
        {{- end }}
      {{- with .Values.api.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity | default .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.priorityClassName | default .Values.global.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- if or .Values.api.cabundle.configMapName .Values.api.cabundle.secretName }}
      initContainers:
      - name: parse-cabundle
        image: {{ include "magos.api.image" . }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        securityContext:
          runAsUser: 0
        command: ["/bin/sh", "-c"]
        args:
        - |
          mkdir -p /usr/local/share/ca-certificates
          for file in /tmp/source/*; do
            base=$(basename "$file" .crt)
            awk 'BEGIN {c=0;} /BEGIN CERT/{c++} { print > "/usr/local/share/ca-certificates/" base "." c ".crt"}' base="$base" < "$file"
          done
          /usr/sbin/update-ca-certificates
          find /etc/ssl/certs -type l -exec cp --remove-destination {} /etc/ssl/certs/ \;
          cp -r /etc/ssl/certs/* /tmp/target/
        volumeMounts:
        - { name: cabundle, mountPath: /tmp/source }
        - { name: certs,    mountPath: /tmp/target }
      volumes:
      - name: cabundle
        {{- if .Values.api.cabundle.secretName }}
        secret:
          secretName: {{ .Values.api.cabundle.secretName }}
        {{- else }}
        configMap:
          name: {{ .Values.api.cabundle.configMapName }}
        {{- end }}
      - name: certs
        emptyDir: {}
      {{- end }}
      terminationGracePeriodSeconds: 30
{{- end }}
