apiVersion: magosproject.io/v1alpha1
kind: Workspace
metadata:
  name: edge-eu-west-prod
  namespace: default
  labels:
    env: prod
    tier: global
    region: eu-west
spec:
  projectRef:
    name: cdn-platform
  serviceAccountName: magos-job
  source:
    repoURL: https://github.com/magosproject/demo.git
    targetRevision: main
    path: .
  terraform:
    version: "1.14.8"
    tfvarsPath: env/prod/vars.tfvars
