{{- if and .Values.api.enabled .Values.logs.enabled .Values.sqlite.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-api-sqlite" (include "magos.fullname" .) }}
  labels:
    {{- include "magos.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  accessModes:
  - ReadWriteOnce
  {{- with .Values.sqlite.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sqlite.persistence.size }}
{{- end }}
