{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "magos.fullname" . }}
  labels:
    {{- include "magos.labels" . | nindent 4 }}
rules:
# Core resources needed by workspace controller
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# Magos CRDs
- apiGroups:
  - magosproject.io
  resources:
  - workspaces
  - projects
  - rollouts
  - variablesets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - magosproject.io
  resources:
  - workspaces/status
  - projects/status
  - rollouts/status
  - variablesets/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - magosproject.io
  resources:
  - workspaces/finalizers
  - projects/finalizers
  - rollouts/finalizers
  - variablesets/finalizers
  verbs:
  - update
{{- end }}
