{{- if .Values.jobServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jobServiceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "magos.labels" . | nindent 4 }}
    app.kubernetes.io/component: job
  {{- with .Values.jobServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.jobServiceAccount.automount }}
{{- end }}
