{{- if eq (include "magos.postgresMode" .) "embedded" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "magos.postgresHeadlessName" . }}
  labels:
    {{- include "magos.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  selector:
    {{- include "magos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
  - name: postgres
    port: {{ .Values.postgres.service.port }}
    targetPort: postgres
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "magos.postgresName" . }}
  labels:
    {{- include "magos.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    {{- include "magos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
  - name: postgres
    port: {{ .Values.postgres.service.port }}
    targetPort: postgres
    protocol: TCP
    {{- if and (eq .Values.postgres.service.type "NodePort") .Values.postgres.service.nodePort }}
    nodePort: {{ .Values.postgres.service.nodePort }}
    {{- end }}
{{- end }}
