{{- if eq (include "magos.logsStorageMode" .) "embedded" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "magos.rustfsName" . }}
  labels:
    {{- include "magos.labels" . | nindent 4 }}
    app.kubernetes.io/component: rustfs
spec:
  type: {{ .Values.logs.storage.service.type }}
  selector:
    {{- include "magos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rustfs
  ports:
  - name: s3
    port: {{ .Values.logs.storage.service.port }}
    targetPort: s3
    protocol: TCP
    {{- if and (eq .Values.logs.storage.service.type "NodePort") .Values.logs.storage.service.nodePort }}
    nodePort: {{ .Values.logs.storage.service.nodePort }}
    {{- end }}
  - name: console
    port: {{ .Values.logs.storage.service.consolePort }}
    targetPort: console
    protocol: TCP
    {{- if and (eq .Values.logs.storage.service.type "NodePort") .Values.logs.storage.service.consoleNodePort }}
    nodePort: {{ .Values.logs.storage.service.consoleNodePort }}
    {{- end }}
{{- end }}
