{{- if .Values.rustfs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-rustfs" (include "magos.fullname" .) }}
  labels:
    {{- include "magos.labels" . | nindent 4 }}
    app.kubernetes.io/component: rustfs
spec:
  accessModes:
  - ReadWriteOnce
  {{- with .Values.rustfs.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.rustfs.persistence.size }}
{{- end }}
