api:
  enabled: false

ui:
  enabled: false

controllers:
  workspace:
    enabled: false
  project:
    enabled: false
  rollout:
    enabled: false
  variableset:
    enabled: false
  refwatcher:
    enabled: false

logs:
  storage:
    auth:
      accessKey: rustfsadmin
      secretKey: ChangeMe123!
    service:
      type: NodePort
      nodePort: 31900
    persistence:
      size: 1Gi

postgres:
  auth:
    password: ChangeMe123!
  service:
    type: NodePort
    nodePort: 31432
