{{- include "magos.validate" . -}}
{{- if .Values.job.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.job.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "magos.labels" . | nindent 4 }}
    {{- include "magos.job.labels" . | nindent 4 }}
    {{- with (mergeOverwrite (deepCopy (default dict .Values.global.labels)) (.Values.job.serviceAccount.labels | default dict)) }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  {{- include "magos.annotations" (dict "root" . "annotations" .Values.job.serviceAccount.annotations) | nindent 2 }}
automountServiceAccountToken: {{ .Values.job.serviceAccount.automount }}
{{- end }}
