apiVersion: magosproject.io/v1alpha1
kind: Workspace
metadata:
  name: dns-dev
  namespace: default
  labels:
    env: dev
  annotations:
    magosproject.io/reconcile-interval: "120s"
spec:
  projectRef:
    name: networking-with-policies
  serviceAccountName: magos-job
  validation:
    policySelector:
      matchLabels:
        policy.magosproject.io/category: network-security
  source:
    repoURL: https://github.com/magosproject/demo.git
    targetRevision: main
    path: .
  terraform:
    version: "1.14.8"
    tfvarsPath: env/dev/vars.tfvars
