apiVersion: magosproject.io/v1alpha1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: magos
    app.kubernetes.io/managed-by: kustomize
  name: workspace-sample
spec:
  source:
    repoURL: https://github.com/magosproject/demo.git
    targetRevision: main
    path: .
  terraform:
    version: "1.14.0"
    tfvarsPath: env/staging/vars.tfvars
  projectRef:
    name: data-platform
