apiVersion: magosproject.io/v1alpha1
kind: VariableSet
metadata:
  labels:
    app.kubernetes.io/name: magos
    app.kubernetes.io/managed-by: kustomize
  name: variableset-sample
spec:
  # TODO(user): Add fields here
