apiVersion: magosproject.io/v1alpha1
kind: Project
metadata:
  name: demo-project
  namespace: default
spec:
  description: Demo project for Magos
  validation:
    policySelector:
      matchExpressions:
        - key: policy.magosproject.io/category
          operator: In
          values:
            - security-1
            - security-2
