apiVersion: magosproject.io/v1alpha1
kind: Workspace
metadata:
  name: demo-prod
  namespace: default
  labels:
    env: prod
  annotations:
    magosproject.io/reconcile-interval: "30s"
spec:
  projectRef:
    name: demo-project
  source:
    repoURL: https://github.com/magosproject/demo.git
    targetRevision: main
    path: .
  terraform:
    version: "1.13.0"
    tfvarsPath: env/staging/vars.tfvars
