apiVersion: magosproject.io/v1alpha1
kind: Workspace
metadata:
  name: demo-staging
  namespace: default
  labels:
    env: dev
  annotations:
    magosproject.io/reconcile-interval: "40s"
spec:
  annotations:
    iam.gke.io/gcp-service-account: "test@test.iam.gserviceaccount.com"
  projectRef:
    name: demo-project
  source:
    repoURL: https://github.com/magosproject/demo.git
    targetRevision: main
    path: .
  terraform:
    version: "1.13.0"
    tfvarsPath: env/staging/vars.tfvars
