apiVersion: magosproject.io/v1alpha1
kind: Workspace
metadata:
  name: demo-prod
  namespace: default
  labels:
    env: prod
  annotations:
    magosproject.io/reconcile-interval: "120s"
spec:
  projectRef:
    name: demo-project
  serviceAccountName: magos-job
  # validation:
  #   policySelector:
  #     matchLabels:
  #       policy.magosproject.io/category: security-1
  #       policy.magosproject.io/category: security-2
  source:
    repoURL: https://github.com/magosproject/demo.git
    targetRevision: main
    path: .
  terraform:
    version: "1.14.8"
    tfvarsPath: env/staging/vars.tfvars
