{{- include "magos.validate" . -}}
{{- $root := . -}}
{{- range $name, $controller := .Values.controllers }}
{{- if and $controller.enabled $controller.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "magos.controllerServiceAccountName" (dict "root" $root "name" $name "controller" $controller) }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "magos.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}-controller
    {{- with (mergeOverwrite (deepCopy (default dict $root.Values.global.labels)) ($controller.serviceAccount.labels | default dict)) }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  {{- include "magos.annotations" (dict "root" $root "annotations" $controller.serviceAccount.annotations) | nindent 2 }}
automountServiceAccountToken: {{ $controller.serviceAccount.automount }}
{{- end }}
{{- end }}
