name: CI - Image - UI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: ui/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build ui image
        uses: docker/build-push-action@v7
        with:
          context: ui
          file: ui/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: type=gha,scope=ci-image-ui
          cache-to: type=gha,mode=max,scope=ci-image-ui
